### ISSUE TITLE
Failed to delete .spark-staging-6 from /HiBench/Terasort/Output2, rc: 2, error msg: No such file or directory

### ISSUE THREAD

**Issue by minmingzhu** [zjf2012/daos#21]
Whether one executor has one core  or one executor has multiple cores , both of them would happened this error : 
 
```
Failed to delete .spark-staging-6 from /HiBench/Terasort/Output2, rc: 2, error msg: No such file or directory

java:226404 terminated with signal 6 at PC=7f1a5addb337 SP=7f0b2dcf3c78.  Backtrace:
/usr/lib64/libc.so.6(gsignal+0x37)[0x7f1a5addb337]
/usr/lib64/libc.so.6(abort+0x148)[0x7f1a5addca28]
/usr/lib64/libc.so.6(+0x78e87)[0x7f1a5ae1de87]
/usr/lib64/libc.so.6(+0x81679)[0x7f1a5ae26679]
/home/spark/daos/install/lib64/libdfs.so(dfs_umount+0xdb)[0x7f0b2c8ec4fb]
/tmp/daos1827901428141704557/libdaos-jni.so(Java_com_intel_daos_client_DaosFsClient_dfsUnmountFs+0x2b)[0x7f0b2d4ef11e]
```

But the directory exists from the dfuse mount directory

**Comment by zjf2012** [comment]
@minmingzhu , "Failed to delete .spark-staging-6 ..." is just a warning message from native code. You can ignore it. And the "terminated" native stack trace is another message when native code crash. It should be caused by too many reading threads put on daos server which has concurrency issue as reproduced by yourself.  We'll wait confirmation from daos team.

**Comment by zjf2012** [comment]
not an issue anymore
